/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'First Steps',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.1,
      timeLimitSeconds: null,
      targetScore: 100,
      obstacleCount: 5,
      obstacleSpeed: 1,
      collectibleCount: 10,
      collectibleValue: 10,
      backgroundTheme: 'City Day',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Picking Up Pace',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: null,
      targetScore: 200,
      obstacleCount: 10,
      obstacleSpeed: 1,
      collectibleCount: 20,
      collectibleValue: 10,
      backgroundTheme: 'Suburban Sunset',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Night Dash',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: null,
      targetScore: 300,
      obstacleCount: 15,
      obstacleSpeed: 2,
      collectibleCount: 30,
      collectibleValue: 10,
      backgroundTheme: 'City Night',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Rising Challenge',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.4,
      timeLimitSeconds: null,
      targetScore: 400,
      obstacleCount: 10,
      obstacleSpeed: 3,
      collectibleCount: 40,
      collectibleValue: 10,
      backgroundTheme: 'Mountain Morning',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Swift Turns',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: null,
      targetScore: 500,
      obstacleCount: 20,
      obstacleSpeed: 4,
      collectibleCount: 50,
      collectibleValue: 10,
      backgroundTheme: 'Forest Day',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Obstacle Rhythm',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: null,
      targetScore: 600,
      obstacleCount: 25,
      obstacleSpeed: 5,
      collectibleCount: 60,
      collectibleValue: 10,
      backgroundTheme: 'Urban Dusk',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'The Great Leap',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: null,
      targetScore: 700,
      obstacleCount: 30,
      obstacleSpeed: 6,
      collectibleCount: 70,
      collectibleValue: 10,
      backgroundTheme: 'Canyon Evening',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Twilight Sprint',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: null,
      targetScore: 800,
      obstacleCount: 35,
      obstacleSpeed: 7,
      collectibleCount: 80,
      collectibleValue: 10,
      backgroundTheme: 'Desert Twilight',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Moonlight Madness',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: null,
      targetScore: 900,
      obstacleCount: 40,
      obstacleSpeed: 8,
      collectibleCount: 90,
      collectibleValue: 10,
      backgroundTheme: 'Mountain Night',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Final Frontier',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 1.0,
      timeLimitSeconds: null,
      targetScore: 1000,
      obstacleCount: 50,
      obstacleSpeed: 10,
      collectibleCount: 100,
      collectibleValue: 10,
      backgroundTheme: 'Space',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
